### ISSUE TITLE
Adding this this to F-Driod

### ISSUE THREAD

**Issue by DonaldTsang** [exzhawk/EhViewer#1]
Is it possible to add this to F-Droid in order for people to easily download the app?
https://f-droid.org/en/ (for those who reads Chinese https://f-droid.org/zh_Hans/)

**Comment by exzhawk** [comment]
Does F-Droid support hosting an app with potential adult content? If no other apps with adult content was hosted on F-Droid previously, I'll be very cautious about doing so.

**Comment by DonaldTsang** [comment]
They already have done it with Hendroid https://f-droid.org/en/packages/org.nonononoki.hendroid/ so it should be okay.

**Comment by exzhawk** [comment]
https://github.com/seven332/EhViewer/issues/439
just noticed ...

**Comment by DonaldTsang** [comment]
1. Firebase can be de-bloated into SQL or some kind or ORM.
2. Licenses can definitely be fixed, or at the very least go for GPLv2
3. Auto-update can be optional, or removed
4. Donation is meh

**Comment by mirh** [comment]
Donation can [actually](https://f-droid.org/en/docs/Inclusion_Policy/) stay there if a gitlab mirror is set up.

**Comment by exzhawk** [comment]
Hippo (the original author of this app) is somehow still active in a community. See #12
I'm not gonna release this to other websites than GitHub(as a fork) unless the name/package name has been changed to avoid misconception.

**Comment by mirh** [comment]
I have seen he's not gone "completely missing", but I don't understand why he froze his repository then.
