### ISSUE TITLE
Implement a way to turn of snapping?

### ISSUE THREAD

**Issue by Quackdoc** [exzhawk/EhViewer#16]
When scrolling in vertical mode, the page always snaps to the top when it gets close enough. is alone is fairly annoying on devices with tall aspect ratios. but it gets worse

this also causes odd behavior scrolling back up, it causes the page to fling to the top. I have pasted a link you a video to better visualize the issue.

I would like to be able to turn off snapping altogether

https://files.catbox.moe/3yw58w.mp4

**Comment by exzhawk** [comment]
fixed in ae1c8963 and released in 1.7.14
the behavior is way too weird, so snapping is disabled by default after updating the app.
