### ISSUE TITLE
Search only lists the first 25 results, does not load more.

### ISSUE THREAD

**Issue by uNderdog101** [exzhawk/EhViewer#19]
**Describe the bug**
When searching only the first 25 result are shown in the list, and scrolling to the bottom does not load additional results.

**To Reproduce**
1. Search
2. scroll to bottom of results
3. No more results

**Expected behavior**
Load additional search results when scrolling to bottom of results.

**Device model and Android version**
 - Device model: [Asus Zenpad]
 - Android version: [Android 5.0.1]
 - App version: 1.7.10

**Additional context**
E-hentai changed the way their search works, which overlaps with when the app stopped working properly: [E-Hentai Forums](https://forums.e-hentai.org/index.php?showtopic=261743)

**Comment by jtm666** [comment]
Found another version that works: https://github.com/xiaojieonly/Ehviewer_CN_SXJ
You can change the language setting at: top left corner > gear icon > android icon > the 7th option (App XXX)

**Comment by Shigbeard** [comment]
@jtm666 this actually doesn't work, the dev of that fork appears to be disrespecting the language setting in many places, with some strings hard coded to Chinese. Additionally, it crashes for me.

**Comment by uNderdog101** [comment]
@jtm666 @Shigbeard 
I just looked a bit closer at that fork, and it requires Android 6.0 as a minimum, that's no good for me.

**Comment by jtm666** [comment]
> @jtm666 this actually doesn't work, the dev of that fork appears to be disrespecting the language setting in many places, with some strings hard coded to Chinese. Additionally, it crashes for me.

Disable "show tag translations".
![image](https://user-images.githubusercontent.com/52636379/200083091-15c6c124-07de-43e9-8b89-3b2f3cb9f9e9.png)
Source: https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/356

**Comment by abvgdeyoj** [comment]
Hath perks "Paging Enlargement I/II/III" affects this, making it 50/100/200 results respectively.
Will take a look at what can be done.

**Comment by abvgdeyoj** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/commit/023988e solves this problem in Ehviewer_CN_SXJ.
I advise to first wait until the [seek navigation](https://forums.e-hentai.org/index.php?showtopic=261743) is deployed on [e-hentai.org](http://e-hentai.org/), which I presume should not take long.

**Comment by abvgdeyoj** [comment]
Solved with https://github.com/exzhawk/EhViewer/commit/441fdbb
