### ISSUE TITLE
 部分標籤無法顯示翻譯

### ISSUE THREAD

**Issue by fricyo** [exzhawk/EhViewer#22]
**简略描述 / Describe the bug**
大概说下是什么问题。

部分標籤無法顯示翻譯
目前發現的都是[混合]或[其它]類的標籤

**如何重现 / To Reproduce**
重现的步骤：
1. 打开什么什么
2. 点击什么什么
3. 出现什么什么问题

打開任意含有該標籤的漫畫，即有此情形

**预期行为 / Expected behavior**
应该是什么样子的？

全部正常顯示翻譯

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。

![Screenshot_2022-12-03-11-28-17-645_com hippo ehviewer](https://user-images.githubusercontent.com/30796677/205420900-2eb6e51a-57f8-4c04-99d3-37b4275093ac.jpg)

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：【比如 Pixel 6 XXXL】 
 - Android 版本：【比如 Android 12.1】 
 - Device model: [e.g. Pixel 6 XXXL]
 - Android version: [e.g. Android 12.1]

Xiaomi 11 Lite 5G NE
Android 12

**备注 / Additional context**
还有什么想说的？

**Comment by exzhawk** [comment]
fixed in 6f0f1f788273b05c0e623e22aebfe894bde6f028
download latest apk
