### ISSUE TITLE
Exhentai not working on Kitkat devices 

### ISSUE THREAD

**Issue by scese250** [exzhawk/EhViewer#8]
Hello, apparently you're one of active person working in EhViewer and I read you do this for personal purpose. Recently the gallery Exhentai doesn't work anymore on kitkat devices, I receive "Network error" when browsing in every section or even when trying to login but E-hentai work normally. 

If isn't much effort, can you to fix this problem? Thanks.

**Comment by exzhawk** [comment]
Reproduce "Network error" again, and click Settings->Advanced->Dump logcat. Send files in prompted "logcat" folder to me. I'll see if I can find anything wrong.

**Comment by scese250** [comment]
Here is
[logcat-2020-06-04-17-40-26-249.txt](https://github.com/exzhawk/EhViewer/files/4732870/logcat-2020-06-04-17-40-26-249.txt)

Apparently it's certificate problem or something; date is fine and even can't navigate in emulator with kitkat.

**Comment by exzhawk** [comment]
Try switching Settings->Advanced->Built-in hosts.txt
e-hentai and exhentai use similar cetificate, it's weird that only one of them goes wrong.

**Comment by scese250** [comment]
No luck 
[logcat-2020-06-06-12-15-02-228.txt](https://github.com/exzhawk/EhViewer/files/4740593/logcat-2020-06-06-12-15-02-228.txt)

**Comment by exzhawk** [comment]
Just tried Android 4.4 on Android Emulator from Android Studio. Can't reproduce the error...

**Comment by scese250** [comment]
Well, it's not something you can reproduce by trying steps, it's a problem that makes unsable Exhentai and you can't login when starting for first time because the Network error, the app becomes useless. 

Using Memu with Android 4.4 you can view the problem thought I assume with Android Studio you can have accurate logs. 

EDIT: I found a temporal fix for this problem on 4chan, credits to anon

> ExHentai apps fix (EhViewer, Tachiyomi, etc.):
> If you're getting a network error or seeing a white page when trying to login in webview then this probably means your device doesn't have the certificates necessary to access e-hentai.
> This happens because these app's webview implementation doesn't show you the untrusted certificate popup you would otherwise see on other browsers, thus not allowing you to accept anyways.
> To solve this, you need to get the site's certificates yourself and install them on your device.
> To get certificates:
> https://www.shellhacks.com/get-ssl-certificate-from-server-site-url-export-download/
> Either the Gandhi or the Usertrust certificates work.
> Then you need to install the certificate. Refer to this guide for instructions:
> https://comodosslstore.com/blog/how-to-install-ssl-certificate-on-android.html
> After that you're done. Panda apps should work again, allowing you to login.
> If anyone here has some android development experience, please make a fork and fix this issue.

**Comment by exzhawk** [comment]
Okay, just found that though certificates of e-hentai and exhentai are issued by the same Gandi Standard SSL CA 2, their certificate chains are slightly different. Maybe that's the point.
Anyway, happy to see you solved the problem!
